apiVersion: v1
kind: Service
metadata:
  name: pin-backend-staging
  labels:
    app: pin-backend
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: pin-backend
    tier: backend
